services:
  - name: web
    env:
      - key: SECRET_KEY
        # Add your Django SECRET_KEY value here
        value: "django-insecure-vi8u#u^v3e2t3ar2)s8b%tj2kt()a%wqtkalt7bpk#dhw4c_ix"
    buildCommand: python manage.py collectstatic --noinput
    staticPublishPath: static
    start_command: "gunicorn sales_funnel_project.wsgi --bind 0.0.0.0:$PORT"
    health_check_path: "/"

databases:
  - name: my-database
    type: postgresql
    plan: free
    config:
      database: sales_funnel_db
      user: neo_breed
      password: M2nny9ImITHg0gTISDrMWfcELQmiyV6q
      host: dpg-cje7fkenk9qs73f0i3qg-a  # Replace with your PostgreSQL host
      port: 5432